"""добавили в form status

Revision ID: 2a0881eb5add
Revises: 5f4edaff7d4f
Create Date: 2025-08-31 18:39:43.105032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0881eb5add'
down_revision: Union[str, Sequence[str], None] = '5f4edaff7d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('form', sa.Column('status', sa.String(), server_default='new', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'status')
    op.drop_column('form', 'created_at')
    # ### end Alembic commands ###
