"""добавили в form столбец comment

Revision ID: 89ba97bb583c
Revises: f7db67849703
Create Date: 2025-08-31 17:32:12.142833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ba97bb583c'
down_revision: Union[str, Sequence[str], None] = 'f7db67849703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'comment')
    # ### end Alembic commands ###
