"""сделали questions уникальными в таблице faq

Revision ID: e94cdeef6150
Revises: 11b412302594
Create Date: 2025-08-31 16:57:27.591711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94cdeef6150'
down_revision: Union[str, Sequence[str], None] = '11b412302594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_faq_question', 'faq', ['question'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_faq_question', 'faq', type_='unique')
    # ### end Alembic commands ###
